baseURL = "https://wike-chi.github.io/"
languageCode = "zh-cn"
title = "Wike's Blog"
theme = "geekdoc"

[params]
  geekdocLogo = ""
  geekdocMenuBundle = true
  geekdocSearch = true
  geekdocTagsToMenu = true

[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.geekdocAnchorRight]
  enable = true
